### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Amzd** [AparokshaUI/Localized#2]
Is there a way to manually generate the Loc type so I can get autocomplete? Rather than it being generated at the compile step.

**Comment by david-swift** [comment]
The plugin calls the [Generation executable](https://github.com/AparokshaUI/Localized/tree/master/Sources/Generation) which you could also call manually in your project directory, specifying the input file's path (`Localized.yml`) as the first argument and the path of the output file (`Localized.swift`) as the second one.

After compiling, you should get autocomplete for the Swift file generated via the plugin without requiring you to run the executable manually.

**Comment by Amzd** [comment]
> After compiling, you should get autocomplete for the Swift file generated via the plugin without requiring you to run the executable manually.

I can't get this to work with sourcekit-lsp, maybe some editors do a trick I am not seeing? I think it is related to this issue https://github.com/apple/sourcekit-lsp/issues/665

I am working around this by adding to my build-commands:
```bash
rm -f Sources/Target/Localized.swift
swift build [...]
ln -s .build/plugins/outputs/folder/Target/GenerateLocalized/Localized.swift Sources/Target/Localized.swift
```
